upstream service_auth {
    server service-auth:8000;
}

upstream service_payment {
    server service-payment:8000;
}

upstream service_product {
    server service-product:8000;
}

server {
    listen 80;

    # CORS headers
    add_header Access-Control-Allow-Origin  *  always;
    add_header Access-Control-Allow-Methods 'GET, POST, PUT, PATCH, DELETE, OPTIONS' always;
    add_header Access-Control-Allow-Headers 'Authorization, Content-Type, Accept' always;

    # Preflight requests
    if ($request_method = OPTIONS) {
        return 204;
    }

    # ── Auth ──────────────────────────────────────────────────────────────────
    location /api/auth/ {
        rewrite ^/api/auth/(.*)$ /api/$1 break;
        proxy_pass         http://service_auth;
        proxy_set_header   Host             $host;
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
    }

    # ── Auth Swagger UI + assets ───────────────────────────────────────────────
    location /api/auth/documentation {
        rewrite ^ /api/documentation break;
        proxy_pass         http://service_auth;
        proxy_set_header   Host             $host;
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
    }

    location /api/auth/docs/ {
        proxy_pass         http://service_auth;
        proxy_set_header   Host             $host;
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
    }

    location /vendor/swagger-api/ {
        proxy_pass         http://service_auth;
        proxy_set_header   Host             $host;
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
    }

    # ── Products ──────────────────────────────────────────────────────────────
    location /api/products/ {
        rewrite ^/api/products/(.*)$ /api/$1 break;
        proxy_pass         http://service_product;
        proxy_set_header   Host             $host;
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
    }

    # ── Payments ──────────────────────────────────────────────────────────────
    location /api/payments/ {
        rewrite ^/api/payments/(.*)$ /api/$1 break;
        proxy_pass         http://service_payment;
        proxy_set_header   Host             $host;
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
    }
}
